apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: identity
resources:
  - ../dev/namespace.yaml
  - postgres.yaml
  - keycloak.yaml
  - networkpolicy.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: haven
      haven.identity/plane: platform
      haven.identity/profile: production
