# Copyright 2026 Zyvor AI Labs
# SPDX-License-Identifier: Apache-2.0
FROM golang:1.22-alpine AS gobuild
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY api/ api/
COPY cmd/haven-controller/ cmd/haven-controller/
COPY internal/ internal/
RUN CGO_ENABLED=0 go build -o /out/haven-controller ./cmd/haven-controller

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=gobuild /out/haven-controller /haven-controller
USER nonroot:nonroot
ENTRYPOINT ["/haven-controller"]
