console:
  enabled: true
  replicas: 1
  clientSecretRotationDays: 90
  persistence:
    enabled: true
    size: 5Gi
    # storageClass: fast-rwo
    accessModes:
      - ReadWriteOnce

controller:
  enabled: true
