#!/usr/bin/env bash
# Copyright 2026 Zyvor AI Labs
# SPDX-License-Identifier: Apache-2.0
# shellcheck shell=bash
# Terminal UI helpers for Axiom deploy-remote.sh.

if [[ -t 1 ]]; then
  _AUI_RESET=$'\033[0m'
  _AUI_BOLD=$'\033[1m'
  _AUI_DIM=$'\033[2m'
  _AUI_CYAN=$'\033[0;36m'
  _AUI_BLUE=$'\033[0;34m'
  _AUI_MAGENTA=$'\033[0;35m'
  _AUI_GREEN=$'\033[0;32m'
  _AUI_YELLOW=$'\033[0;33m'
  _AUI_RED=$'\033[0;31m'
  _AUI_WHITE=$'\033[0;97m'
else
  _AUI_RESET=''
  _AUI_BOLD=''
  _AUI_DIM=''
  _AUI_CYAN=''
  _AUI_BLUE=''
  _AUI_MAGENTA=''
  _AUI_GREEN=''
  _AUI_YELLOW=''
  _AUI_RED=''
  _AUI_WHITE=''
fi

AXIOM_DEPLOY_START=${SECONDS:-0}
_AXIOM_UI_STEP=0
_AXIOM_UI_TOTAL=6

axiom_ui_set_total() {
  _AXIOM_UI_TOTAL="${1:-6}"
}

axiom_ui_elapsed() {
  local s=$((SECONDS - AXIOM_DEPLOY_START))
  printf '%02d:%02d' $((s / 60)) $((s % 60))
}

axiom_ui_banner() {
  local title="${1:-Zyvor Axiom Remote Deploy}"
  local subtitle="${2:-}"
  echo ""
  echo "${_AUI_MAGENTA}${_AUI_BOLD}  ╔══════════════════════════════════════════════════════════════════╗${_AUI_RESET}"
  echo "${_AUI_MAGENTA}${_AUI_BOLD}  ║${_AUI_RESET}  ${_AUI_CYAN}${_AUI_BOLD}◆  ${title}${_AUI_RESET}$(printf '%*s' $((58 - ${#title})) '')${_AUI_MAGENTA}${_AUI_BOLD}║${_AUI_RESET}"
  if [[ -n "$subtitle" ]]; then
    echo "${_AUI_MAGENTA}${_AUI_BOLD}  ║${_AUI_RESET}  ${_AUI_DIM}${subtitle}${_AUI_RESET}$(printf '%*s' $((58 - ${#subtitle})) '')${_AUI_MAGENTA}${_AUI_BOLD}║${_AUI_RESET}"
  fi
  echo "${_AUI_MAGENTA}${_AUI_BOLD}  ╚══════════════════════════════════════════════════════════════════╝${_AUI_RESET}"
  echo ""
}

axiom_ui_kv() {
  local key="$1" val="$2"
  printf "  ${_AUI_DIM}%-12s${_AUI_RESET} %s\n" "${key}:" "${val}"
}

axiom_ui_progress() {
  local current="$1" total="$2"
  local width=28
  local filled=$((current * width / total))
  local empty=$((width - filled))
  local pct=$((current * 100 / total))
  printf "  ${_AUI_BLUE}["
  printf '%*s' "$filled" '' | tr ' ' '█'
  printf '%*s' "$empty" '' | tr ' ' '░'
  printf "]${_AUI_RESET} ${_AUI_DIM}%3d%%${_AUI_RESET}  ${_AUI_DIM}elapsed %s${_AUI_RESET}\n" "$pct" "$(axiom_ui_elapsed)"
}

axiom_ui_step() {
  _AXIOM_UI_STEP="$1"
  local total="${2:-$_AXIOM_UI_TOTAL}"
  local label="${3:-}"
  echo ""
  axiom_ui_progress "$_AXIOM_UI_STEP" "$total"
  echo "${_AUI_CYAN}${_AUI_BOLD}  ▶ Step ${_AXIOM_UI_STEP}/${total}${_AUI_RESET}  ${label}"
  echo "${_AUI_DIM}  ────────────────────────────────────────────────────────────────${_AUI_RESET}"
}

info()  { echo "${_AUI_GREEN}  ✓${_AUI_RESET} $*"; }
warn()  { echo "${_AUI_YELLOW}  ⚠${_AUI_RESET}  $*"; }
error() { echo "${_AUI_RED}  ✗${_AUI_RESET} $*"; exit 1; }
step()  { axiom_ui_step "$@"; }

axiom_ui_success() {
  local host="$1" user="$2"
  echo ""
  echo "${_AUI_GREEN}${_AUI_BOLD}  ╔══════════════════════════════════════════════════════════════════╗${_AUI_RESET}"
  echo "${_AUI_GREEN}${_AUI_BOLD}  ║${_AUI_RESET}  ${_AUI_WHITE}${_AUI_BOLD}🎉  Deployment complete${_AUI_RESET}  ${_AUI_DIM}${user}@${host}${_AUI_RESET}$(printf '%*s' $((35 - ${#user} - ${#host})) '')${_AUI_GREEN}${_AUI_BOLD}║${_AUI_RESET}"
  echo "${_AUI_GREEN}${_AUI_BOLD}  ║${_AUI_RESET}  ${_AUI_DIM}Total time: $(axiom_ui_elapsed)${_AUI_RESET}$(printf '%*s' 44 '')${_AUI_GREEN}${_AUI_BOLD}║${_AUI_RESET}"
  echo "${_AUI_GREEN}${_AUI_BOLD}  ╚══════════════════════════════════════════════════════════════════╝${_AUI_RESET}"
  echo ""
}

axiom_ui_panel() {
  local title="$1"
  shift
  echo ""
  echo "${_AUI_BOLD}  ┌─ ${title}${_AUI_RESET}"
  while [[ $# -gt 0 ]]; do
    echo "  │  $1"
    shift
  done
  echo "${_AUI_BOLD}  └──────────────────────────────────────────────────────────────${_AUI_RESET}"
}

axiom_deploy_state_file() {
  echo "$1/.deploy-last"
}

axiom_save_deploy_last() {
  local repo_dir="$1" host="$2" user="$3" mode="$4" tag="${5:-dev}"
  local f
  f=$(axiom_deploy_state_file "$repo_dir")
  cat >"$f" <<EOF
# Auto-generated by Axiom deploy (no passwords)
HOST=$host
USER=$user
MODE=$mode
IMAGE_TAG=$tag
UPDATED=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
EOF
  chmod 600 "$f" 2>/dev/null || true
}

axiom_load_deploy_last() {
  local repo_dir="$1" f
  f=$(axiom_deploy_state_file "$repo_dir")
  [ -f "$f" ] || return 1
  # shellcheck disable=SC1090
  source "$f"
  return 0
}
