server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /config.json {
        add_header Cache-Control "no-store";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/css application/javascript application/json;
}
