{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: haven
    app.kubernetes.io/component: controller
{{- end }}
